var PAGES = [
	{url: "page0.htm"},
	{url: "page1.htm"},
	{url: "page1_1.htm"},
	{url: "page1_2.htm"},
	{url: "page1_3.htm"},
	{url: "page2.htm"},
	{url: "page3.htm"},
	{url: "page3_1.htm"},
	{url: "page3_2.htm"},
	{url: "page3_3.htm"},
	{url: "page3_4.htm"},
	{url: "part1_conclusions.htm", slides:["#s1", "#s2", "#s3"]},
	{url: "page4.htm", slides:["#s1", "#s2", "#s3", "#s4", "#s5", "#s6", "#s7"]},
	{url: "page4_1.htm"},
	{url: "page4_2.htm"},
	{url: "page4_3.htm"},
	{url: "page4_4.htm"},
	{url: "page4_5.htm"},
	{url: "page4_6.htm", slides:["#s1", "#s2"]},
	{url: "page4_7.htm"},
	{url: "page4_8.htm"},
	{url: "page4_9.htm"},
	{url: "page4_10.htm"},
	{url: "page4_11.htm"},
	{url: "page4_12.htm"},
	{url: "page4_13.htm"},
	{url: "page4_14.htm"},
	{url: "page5.htm", slides:["#s1"]},
	{url: "page6.htm"},
	{url: "page7.htm"}
];